/**
 * In-memory fixtures for the HIM Intake & Identity stream. Mutated by
 * `api.ts` so the demo feels live within a session (no persistence).
 */
import type {
  CoverageStatus,
  HimActivityEvent,
  HimSession,
  HimSummary,
  HimWorklistItem,
  MciCasualty,
  MciEvent,
  PatientSearchResult,
} from './types'

export const FACILITIES = [
  'Garki General Hospital',
  'Ikeja Medical Centre',
  'Kano Specialist Clinic',
  'Enugu Teaching Hospital',
]

export const CURRENT_HIM_USER: HimSession = {
  id: 'h-000',
  name: 'Umair Ibrahim',
  title: 'HIM Officer',
  facilities: FACILITIES,
  permissions: [
    'him.dashboard.view',
    'patient.search',
    'patient.read',
    'patient.register',
    'patient.register.emergency',
    'patient.register.neonate',
    'patient.register.offline',
    'patient.duplicate.override',
    'patient.identifier.manage',
    'patient.identifier.verify',
    'patient.identifier.unmask',
    'patient.relatedperson.manage',
    'patient.verify',
    'patient.demographics.update',
    'patient.identity.update',
    'patient.mci.manage',
    'encounter.create',
    'encounter.checkin',
    'queue.route',
    'him.offline.view',
    'him.offline.reconcile',
    'him.migration.manage',
    'him.migration.rehearse',
    'him.migration.commit',
  ],
}

export const HIM_WORKLIST: HimWorklistItem[] = [
  {
    id: 'w1',
    patientId: 'p12',
    type: 'incomplete',
    patientName: 'Unknown-Male-0231',
    mrn: undefined,
    ageHours: 6,
    detailTo: '/him/worklists/incomplete',
    assignedToMe: true,
    facility: 'Garki General Hospital',
  },
  {
    id: 'w2',
    patientId: 'p6',
    type: 'incomplete',
    patientName: 'Baby of Hauwa Musa',
    mrn: '004-9910',
    ageHours: 22,
    detailTo: '/him/worklists/incomplete',
    assignedToMe: false,
    facility: 'Kano Specialist Clinic',
  },
  {
    id: 'w7',
    patientId: 'p1',
    type: 'incomplete',
    patientName: 'Ngozi Eze',
    mrn: '004-2213',
    ageHours: 9,
    detailTo: '/him/worklists/incomplete',
    assignedToMe: false,
    facility: 'Garki General Hospital',
  },
  {
    id: 'w8',
    patientId: 'p11',
    type: 'incomplete',
    patientName: 'Zainab Lawal',
    mrn: '004-1830',
    ageHours: 3,
    detailTo: '/him/worklists/incomplete',
    assignedToMe: true,
    facility: 'Ikeja Medical Centre',
  },
  {
    id: 'w3',
    patientId: 'p3',
    type: 'duplicates',
    patientName: 'Sani Ahmed',
    mrn: '004-3320',
    ageHours: 4,
    detailTo: '/him/worklists/duplicates',
    assignedToMe: true,
    facility: 'Kano Specialist Clinic',
  },
  {
    id: 'w4',
    patientId: 'p9',
    type: 'duplicates',
    patientName: 'Fatima Bello',
    mrn: '004-0733',
    ageHours: 30,
    detailTo: '/him/worklists/duplicates',
    assignedToMe: false,
    facility: 'Kano Specialist Clinic',
  },
  {
    id: 'w9',
    patientId: 'p4',
    type: 'duplicates',
    patientName: 'Amara Nwosu',
    mrn: '004-0916',
    ageHours: 15,
    detailTo: '/him/worklists/duplicates',
    assignedToMe: false,
    facility: 'Enugu Teaching Hospital',
  },
  {
    id: 'w5',
    patientId: 'p5',
    type: 'release',
    patientName: 'Tunde Bakare',
    mrn: '004-2744',
    ageHours: 12,
    detailTo: '/him/worklists/release',
    assignedToMe: false,
    facility: 'Ikeja Medical Centre',
  },
  {
    id: 'w10',
    patientId: 'p8',
    type: 'release',
    patientName: 'Yemi Adeola',
    mrn: '004-3491',
    ageHours: 5,
    detailTo: '/him/worklists/release',
    assignedToMe: true,
    facility: 'Garki General Hospital',
  },
  {
    id: 'w6',
    patientId: 'p2',
    type: 'dsar',
    patientName: 'Efe Ojo',
    mrn: '004-1187',
    ageHours: 48,
    detailTo: '/him/worklists/dsar',
    assignedToMe: false,
    facility: 'Ikeja Medical Centre',
  },
  {
    id: 'w11',
    patientId: 'p9',
    type: 'dsar',
    patientName: 'Fatima Bello',
    mrn: '004-0733',
    ageHours: 60,
    detailTo: '/him/worklists/dsar',
    assignedToMe: true,
    facility: 'Enugu Teaching Hospital',
  },
]

const countByType = (type: HimWorklistItem['type']) =>
  HIM_WORKLIST.filter((w) => w.type === type).length

export const HIM_SUMMARY: HimSummary = {
  registrationsToday: 34,
  incompleteRecords: countByType('incomplete'),
  duplicateCandidates: countByType('duplicates'),
  pendingReleaseRequests: countByType('release'),
  openDsars: countByType('dsar'),
  breakGlassToReview: 1,
}

export const HIM_RECENT_ACTIVITY: HimActivityEvent[] = [
  {
    id: 'a1',
    actor: 'Umair Ibrahim',
    action: 'Registered new patient',
    targetLabel: 'Amara Nwosu · 004-0916',
    targetPatientId: 'p4',
    occurredAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: 'a2',
    actor: 'Chinedu Okoro',
    action: 'Verified NIN identifier',
    targetLabel: 'Sani Ahmed · 004-3320',
    targetPatientId: 'p3',
    occurredAt: new Date(Date.now() - 47 * 60 * 1000).toISOString(),
  },
  {
    id: 'a3',
    actor: 'Umair Ibrahim',
    action: 'Flagged duplicate candidate',
    targetLabel: 'Fatima Bello · 004-0733',
    targetPatientId: 'p9',
    occurredAt: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
  },
  {
    id: 'a4',
    actor: 'Blessing Eze',
    action: 'Opened break-glass access',
    targetLabel: 'Yemi Adeola · 004-3491',
    targetPatientId: 'p8',
    occurredAt: new Date(Date.now() - 130 * 60 * 1000).toISOString(),
  },
  {
    id: 'a5',
    actor: 'Umair Ibrahim',
    action: 'Merged duplicate record',
    targetLabel: 'Ikenna Obi → Efe Ojo',
    targetPatientId: 'p2',
    occurredAt: new Date(Date.now() - 260 * 60 * 1000).toISOString(),
  },
]
interface SeedPatient {
  id: string
  mrn: string
  fullName: string
  age: number | null
  sex: 'M' | 'F' | 'O' | 'unknown'
  phone: string
  facility: string
  lastVisit: string | null
  statusFlags: PatientSearchResult['statusFlags']
  mergedIntoId?: string
  dateOfBirth: string | null
  allergies: string[]
  coverage: { payer: string; status: CoverageStatus } | null
  address?: string
}

export const HIM_PATIENTS: SeedPatient[] = [
  {
    id: 'p1',
    mrn: '004-2213',
    fullName: 'Ngozi Eze',
    age: 34,
    sex: 'F',
    phone: '0803 221 4410',
    facility: 'Garki General Hospital',
    lastVisit: '12 Jun 2026',
    statusFlags: [],
    dateOfBirth: '14 Mar 1992',
    allergies: ['Penicillin'],
    coverage: { payer: 'Hygeia HMO', status: 'active' },
  },
  {
    id: 'p2',
    mrn: '004-1187',
    fullName: 'Efe Ojo',
    age: 41,
    sex: 'M',
    phone: '0805 114 8890',
    facility: 'Ikeja Medical Centre',
    lastVisit: '28 Jun 2026',
    statusFlags: [],
    dateOfBirth: '02 Aug 1984',
    allergies: [],
    coverage: { payer: 'AXA Mansard', status: 'active' },
  },
  {
    id: 'p3',
    mrn: '004-3320',
    fullName: 'Sani Ahmed',
    age: 58,
    sex: 'M',
    phone: '0806 733 0021',
    facility: 'Kano Specialist Clinic',
    lastVisit: '01 Jul 2026',
    statusFlags: [],
    dateOfBirth: '21 Jan 1968',
    allergies: ['Sulpha drugs'],
    coverage: { payer: 'Leadway Health', status: 'active' },
  },
  {
    id: 'p4',
    mrn: '004-0916',
    fullName: 'Amara Nwosu',
    age: 27,
    sex: 'F',
    phone: '0809 445 6672',
    facility: 'Enugu Teaching Hospital',
    lastVisit: '19 May 2026',
    statusFlags: [],
    dateOfBirth: '30 Nov 1998',
    allergies: [],
    coverage: { payer: 'Hygeia HMO', status: 'active' },
  },
  {
    id: 'p5',
    mrn: '004-2744',
    fullName: 'Tunde Bakare',
    age: 63,
    sex: 'M',
    phone: '0802 998 1145',
    facility: 'Ikeja Medical Centre',
    lastVisit: '03 Jul 2026',
    statusFlags: [],
    dateOfBirth: '17 May 1963',
    allergies: ['Aspirin (GI upset)'],
    coverage: { payer: 'AXA Mansard', status: 'active' },
  },
  {
    id: 'p6',
    mrn: '004-1502',
    fullName: 'Hauwa Musa',
    age: 29,
    sex: 'F',
    phone: '0810 220 7789',
    facility: 'Kano Specialist Clinic',
    lastVisit: '30 Jun 2026',
    statusFlags: [],
    dateOfBirth: '08 Sep 1996',
    allergies: [],
    coverage: { payer: 'Reliance HMO', status: 'active' },
  },
  {
    id: 'p7',
    mrn: '004-2088',
    fullName: 'Chidi Okafor',
    age: 45,
    sex: 'M',
    phone: '0803 667 2210',
    facility: 'Garki General Hospital',
    lastVisit: '11 Apr 2026',
    statusFlags: ['deceased'],
    dateOfBirth: '25 Jun 1981',
    allergies: [],
    coverage: null,
  },
  {
    id: 'p8',
    mrn: '004-3491',
    fullName: 'Yemi Adeola',
    age: 36,
    sex: 'F',
    phone: '0807 118 9034',
    facility: 'Enugu Teaching Hospital',
    lastVisit: '25 Jun 2026',
    statusFlags: ['restricted'],
    dateOfBirth: '12 Feb 1990',
    allergies: ['Dust mites (rhinitis)'],
    coverage: { payer: 'Reliance HMO', status: 'active' },
  },
  {
    id: 'p9',
    mrn: '004-0733',
    fullName: 'Fatima Bello',
    age: 52,
    sex: 'F',
    phone: '0805 442 1178',
    facility: 'Kano Specialist Clinic',
    lastVisit: '02 Feb 2026',
    statusFlags: [],
    dateOfBirth: '19 Jul 1974',
    allergies: ['Ibuprofen'],
    coverage: { payer: 'AIICO Multishield', status: 'expired' },
  },
  {
    id: 'p10',
    // Non-survivor after merge into p2 — original MRN must stay on the record and stay reserved
    // (Jira: deleted/merged retain original MRN · FR-HIM-ID-007 / FR-HIM-MRG-001).
    mrn: '004-2951',
    fullName: 'Ikenna Obi',
    age: 38,
    sex: 'M',
    phone: '0809 001 3345',
    facility: 'Garki General Hospital',
    lastVisit: '04 Jul 2026',
    statusFlags: ['merged'],
    mergedIntoId: 'p2',
    dateOfBirth: '03 Apr 1988',
    allergies: [],
    coverage: null,
  },
  {
    id: 'p11',
    mrn: '004-1830',
    fullName: 'Zainab Lawal',
    age: 31,
    sex: 'F',
    phone: '0810 556 2290',
    facility: 'Ikeja Medical Centre',
    lastVisit: '05 Jul 2026',
    statusFlags: [],
    dateOfBirth: '27 Oct 1994',
    allergies: [],
    coverage: { payer: 'Hygeia HMO', status: 'active' },
  },
  {
    id: 'p12',
    mrn: 'TEMP-0231',
    fullName: 'Unknown-Male-0231',
    age: null,
    sex: 'unknown',
    phone: '',
    facility: 'Garki General Hospital',
    lastVisit: null,
    statusFlags: ['temporary'],
    dateOfBirth: null,
    allergies: [],
    coverage: null,
  },
]
export const MCI_EVENTS: MciEvent[] = []
export const MCI_CASUALTIES: MciCasualty[] = []
