// KpiCard is intentionally NOT re-exported here: it renders an AreaChart, so
// the barrel would pull recharts into every screen that uses any block.
// Import it directly from './KpiCard'.
export { PatientBanner, VitalsRow } from './PatientBanner'
export { RecordBanner } from './RecordBanner'
export { FilterBar } from './FilterBar'
export { Timeline } from './Timeline'
export type { TimelineEvent } from './Timeline'
export { NotificationCenter } from './NotificationCenter'
export type { NotificationItem, NotificationSeverity } from './NotificationCenter'
export { SidebarNav } from './SidebarNav'
export type { SidebarNavItem } from './SidebarNav'
export { ErrorPage } from './ErrorPage'
export { AccountSwitcher } from './AccountSwitcher'
export type { AccountOption } from './AccountSwitcher'
export { FacilitySwitcher } from './FacilitySwitcher'
export type { FacilityOption } from './FacilitySwitcher'
export { ModuleSwitcher, ModuleCardList, ModuleSwitchOverlay } from './ModuleSwitcher'
export type { ModuleOption } from './ModuleSwitcher'
export { FloatingDock, FloatingPill, floatingPillClass } from './FloatingDock'
export { SelectionBar } from './SelectionBar'
export { PageHeader } from './AppPageHeader'
export { AppNavbar } from './AppNavbar'
export { UserMenu } from './UserMenu'
export { ProfileSettings } from './ProfileSettings'
export type { ProfileUser } from './ProfileSettings'
